import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, BookOpen, Check, Database, PhoneCall, ShieldCheck, Sparkles } from "lucide-react";

export default async function Home({ searchParams }: { searchParams: Promise<{ invite?: string }> }) {
  const { invite } = await searchParams;
  if (invite) redirect(`/login?invite=${encodeURIComponent(invite)}`);
  return <main className="landing-shell">
    <header className="landing-nav"><Link className="wordmark" href="/"><span className="signal-mark"><i/><i/><i/></span><strong>asyncfounders</strong><b>.</b></Link><nav><a href="#product">Product</a><a href="#memory">Memory</a><a href="#safety">Safety</a></nav><div><Link className="landing-login" href="/login">Sign in</Link><Link className="primary" href="/login">Start your company <ArrowRight/></Link></div></header>
    <section className="landing-hero"><div className="landing-grid"/><div className="landing-copy"><span className="eyebrow"><Sparkles/>THE OPERATING MEMORY FOR ASYNC FOUNDERS</span><h1>Your company should not forget <em>between conversations.</em></h1><p>Speak when it suits you. AsyncFounders turns founder updates, source material and unresolved questions into one versioned company state—then briefs the next person with the context that actually matters.</p><div className="landing-actions"><Link className="primary" href="/login">Build your company memory <ArrowRight/></Link><a className="secondary" href="#product">See how it works</a></div><div className="landing-trust"><span><ShieldCheck/>Private by company</span><span><Database/>Evidence stays attached</span><span><PhoneCall/>Consent before every call</span></div></div><div className="landing-ledger"><div className="ledger-top"><span>ACME / LIVE STATE</span><b>v42</b></div><article><span className="memory-kind decision">decision</span><div><small>VERSION 42 · 4 MIN AGO</small><h3>Private beta stays capped at ten teams</h3><p>Accepted after founder review. Evidence: customer pipeline and onboarding capacity.</p></div><Check/></article><article><span className="memory-kind conflict">conflict</span><div><small>VERSION 41 · OPEN</small><h3>Pricing signal is still disputed</h3><p>Two founders read the same customer calls differently. Both positions remain visible.</p></div></article><article><span className="memory-kind question">question</span><div><small>VERSION 40 · UNANSWERED</small><h3>Who owns the migration window?</h3><p>CALL-E will carry this unknown forward instead of filling in an answer.</p></div></article><div className="ledger-call"><span className="pulse-mini"><PhoneCall/></span><div><small>CALL-E IS READY</small><b>“Catch me up before the investor call.”</b></div><ArrowRight/></div></div>
    </section>
    <section className="landing-strip"><span>Not meeting notes.</span><span>Not a transcript dump.</span><strong>A shared, inspectable version of reality.</strong></section>
    <section id="product" className="landing-process"><div><span className="eyebrow">HOW IT COMPOUNDS</span><h2>Context enters once.<br/>The whole company gets smarter.</h2></div><ol><li><b>01</b><Database/><h3>Index the real sources</h3><p>Upload notes, documents and public links. Text is cleaned, chunked and kept inside the company boundary.</p></li><li><b>02</b><PhoneCall/><h3>Talk naturally</h3><p>CALL-E knows your current memory and sources. She follows useful threads instead of reading a questionnaire.</p></li><li><b>03</b><BookOpen/><h3>Keep typed memory</h3><p>Facts, ideas, assumptions, decisions, questions, tasks and conflicts stay distinct, versioned and acknowledged.</p></li></ol></section>
    <section id="memory" className="landing-memory"><div className="memory-statement"><span className="eyebrow">MEMORY WITH CONSEQUENCES</span><h2>A decision is not an idea with better marketing.</h2><p>AsyncFounders preserves lifecycle, evidence, confidence, author, audience and disagreement. Every founder can see what changed, what remains unknown and what they personally have not reviewed.</p><Link className="secondary" href="/login">Open a clean workspace <ArrowRight/></Link></div><div className="type-stack">{[["FACT","Supported and current"],["IDEA","Worth exploring"],["ASSUMPTION","Needs evidence"],["DECISION","Explicitly accepted"],["CONFLICT","Positions preserved"],["QUESTION","Unknown stays unknown"]].map(([type,copy],index)=><span key={type} style={{transform:`translateX(${index%2?28:0}px)`}}><b>{type}</b><small>{copy}</small></span>)}</div></section>
    <section id="safety" className="landing-safety"><div><ShieldCheck/><span className="eyebrow">PRODUCTION BOUNDARIES</span><h2>Useful enough to trust.<br/>Constrained enough to inspect.</h2></div><ul><li><Check/><span><b>Company isolation</b>Membership-gated rows and private source storage.</span></li><li><Check/><span><b>Your number stays yours</b>Self-only callback identity; teammates see only the last four digits.</span></li><li><Check/><span><b>No surprise calls</b>Previewed, explicitly confirmed and payload-idempotent.</span></li><li><Check/><span><b>Unknowns survive</b>Low-confidence or malformed results fail closed.</span></li></ul></section>
    <section className="landing-cta"><span className="signal-mark"><i/><i/><i/></span><h2>Stop reconstructing the company from memory.</h2><p>Give the team one source-backed state that keeps moving when calendars do not.</p><Link className="primary" href="/login">Start AsyncFounders <ArrowRight/></Link></section>
    <footer className="landing-footer"><Link className="wordmark" href="/"><span className="signal-mark"><i/><i/><i/></span><strong>asyncfounders</strong><b>.</b></Link><p>Talk once. The company remembers.</p><Link href="/login">Sign in</Link></footer>
  </main>;
}
